### ISSUE TITLE
Sys - Migrate from deprecated APIs

### ISSUE THREAD

**Issue by CristiSch** [visual-space/visual-editor#211] opened 2023-03-28 10:09 UTC
Certain Flutter APIs have been deprecated and need to be refactored using the new practices.

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/25954636/228203386-eb00ce52-819f-4c99-9da3-2c63ef94a532.png">

**Comment by adrian-moisa** [comment] 2023-08-26 17:52
Duplicate of #229

**Closed as completed by adrian-moisa** 2023-08-26 17:52 UTC
Labels: duplicate
