### ISSUE TITLE
Selection - Restore copy paste styled text

### ISSUE THREAD

**Issue by darius859** [visual-space/visual-editor#218] opened 2023-04-01 19:20 UTC
Looks like it is working on mobile, but not on web.

  void copySelection(SelectionChangedCause cause) {
    state.paste.copiedImageUrl = null;
    state.paste.plainText = _editorService.getSelectionPlainText();
    state.paste.styles = _stylesService.getAllIndividualSelectionStyles();

**Comment by adrian-moisa** [comment] 2024-01-23 21:16
Duplicate of #8

**Closed as completed by adrian-moisa** 2024-01-23 21:16 UTC
Labels: duplicate
