### ISSUE TITLE
Highlights - Unable to delete characters, entering shifts highlight

### ISSUE THREAD

**Issue by werkmann** [visual-space/visual-editor#221] opened 2023-05-25 13:40 UTC
O OSX Ventura 13.2 (22D49)
clean checkout (commit 6ccbb581), now inside example I execute
flutter run -d  macOS
platform:macOS, arch:arm64,

I have the following problem:
I am unable to delete any characters using the backspace key. 
Also, with every single character I enter, the highlight in the paragraph immediately following my position, as well as in all subsequent paragraphs, is shifted left. This is not true for the blueish highlight. 

In console. 
[NSTextView layout] failed to converge after 5 iterations

**Comment by adrian-moisa** [comment] 2023-05-25 16:05
Thank you for reporting! Can you share a gif/vid of your issue. Seems rather odd. I'd expect backspace to work.

**Comment by siliconsorcery** [comment] 2023-05-27 15:34
I can confirm,
macOS Ventura 13.2.1

terminal 
git clone https://github.com/visual-space/visual-editor.git
cd example

flutter doctor
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!

flutter clean
Cleaning Xcode workspace...                                      1,144ms
Cleaning Xcode workspace...                                      1,757ms
Deleting build...                                                             55ms
Deleting .dart_tool...                                                     2ms
Deleting Generated.xcconfig...                                    0ms
Deleting flutter_export_environment.sh...                  0ms
Deleting ephemeral...                                                   0ms
Deleting .flutter-plugins-dependencies...                  0ms
Deleting .flutter-plugins...                                           0ms

flutter run -d macos
Running "flutter pub get" in example...
Resolving dependencies... 
  _fe_analyzer_shared 38.0.0 (61.0.0 available)
  analyzer 3.4.1 (5.13.0 available)
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.2 available)
  device_info_plus 3.2.4 (9.0.1 available)
  device_info_plus_linux 2.1.1 (5.0.0 available)
  device_info_plus_macos 2.2.3 (5.0.0 available)
  device_info_plus_platform_interface 2.6.1 (7.0.0 available)
  device_info_plus_web 2.1.0 (5.0.0 available)
  device_info_plus_windows 2.1.1 (6.0.0 available)
  ffi 1.2.1 (2.0.2 available)
  file 6.1.4 (7.0.0 available)
  file_picker 4.6.1 (5.3.2 available)
  filesystem_picker 2.0.1 (3.1.0 available)
  google_fonts 3.0.1 (4.0.5 available)
  http 0.13.6 (1.0.0 available)
  i18n_extension 4.2.1 (9.0.0 available)
  intl 0.17.0 (0.18.1 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  meta 1.8.0 (1.9.1 available)
  path 1.8.2 (1.8.3 available)
  path_provider_windows 2.0.7 (2.1.6 available)
  photo_view 0.13.0 (0.14.0 available)
  source_span 1.9.1 (1.10.0 available)
  sprintf 6.0.2 (7.0.0 available)
  string_validator 0.3.0 (1.0.0 available)
  test_api 0.4.16 (0.6.0 available)
  watcher 1.0.2 (1.1.0 available)
  win32 2.6.1 (5.0.2 available)
Got dependencies!
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             724ms
2023-05-27 08:22:02.957 xcodebuild[62618:8518867] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx }
{ platform:macOS, arch:arm64, id:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...                                           
Syncing files to device macOS...                                   226ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:49767/VA9oDlKkVPI=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:49767/VA9oDlKkVPI=/

* Placed carat at end of 'Custom highlights
* None for the follow worked ... tried keyboard backspace, delete, cursor up, cursor down, cursor left, cursor right, undo, redo.

No point in creating a gif/vid. There is nothing to see!

Hope this helps.

**Comment by darius859** [comment] 2023-05-27 18:18
Looks like the issue appears only on mac, in windows the backspace works as expected. 

When it comes to the highlight, we know about the issue https://github.com/visual-space/visual-editor/issues/200

We are working on it.

**Comment by garv-shah** [comment] 2023-06-27 09:36
Can confirm the issue, neither backspace, highlight or navigation with the arrow keys works on MacOS as of now

**Comment by adrian-moisa** [comment] 2023-08-26 17:48
We will have a look and fix it. However we are fully booked for the next 2 months. If you have a PR in the meantime I'll double check it. Thank you!

**Comment by adrian-moisa** [comment] 2024-01-28 15:44
Duplicates #200

**Closed as completed by adrian-moisa** 2024-01-28 15:44 UTC
Labels: duplicate
